### PR TITLE
Get rid of PrimitiveKind.UNIT and corresponding encoder methods

### LINKED ISSUE #645: ArrayIndexOutOfBoundsException while deserializing Unit from JsonObject
**Describe the bug**
When attempting to deserialize Unit (using UnitSerializer) from a JsonElement with `fromJson`, the following exception is thrown:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.remove(ArrayList.java:499)
	at kotlinx.serialization.TaggedDecoder.popTag(Tagged.kt:252)
	at kotlinx.serialization.TaggedDecoder.decodeUnit(Tagged.kt:184)
	at kotlinx.serialization.internal.UnitSerializer.deserialize(Primitives.kt:38)
	at kotlinx.serialization.internal.UnitSerializer.deserialize(Primitives.kt:34)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:41)
	at kotlinx.serialization.CoreKt.decode(Core.kt:80)
	at kotlinx.serialization.json.internal.TreeJsonInputKt.readJson(TreeJsonInput.kt:20)
	at kotlinx.serialization.json.Json.fromJson(Json.kt:146)
	at UnmapperTest.unmapUnitViaJsonElement(UnmapperTest.kt:18)
...
```

**To Reproduce**
```kotlin
class UnmapperTest {
    private val json = Json(JsonConfiguration.Stable)

    @Test
    fun unmapUnitViaString() {
        assertEquals(Unit, json.parse(UnitSerializer, "{}"))
    }

    @Test
    fun unmapUnitViaJsonElement() {
        assertEquals(Unit, json.fromJson(UnitSerializer, JsonObject(emptyMap())))
    }
}
```

**Expected behavior**
Both tests should pass. Actual behavior is that `unmapUnitViaJsonElement` fails with above exception, while `unmapUnitViaString` succeeds as expected.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms:  JVM
 - Gradle version: 6.0.1

### PR DESCRIPTION
**Pull request by qwwdfsad**
* Treat Unit as a regular Kotlin object which Unit is.
  * Ensure SerialDescriptor invariants in ObjectDescriptor

Also, fixes #645

### CODE REVIEW

File: runtime/commonMain/src/kotlinx/serialization/ElementWise.kt [hunk 1]
```diff
@@ -54,8 +52,17 @@ abstract class ElementValueEncoder : Encoder, CompositeEncoder {
 
     // Delegating implementation of CompositeEncoder
 
-    final override fun encodeNonSerializableElement(desc: SerialDescriptor, index: Int, value: Any) { if (encodeElement(desc, index)) encodeValue(value) }
-    final override fun encodeUnitElement(desc: SerialDescriptor, index: Int) { if (encodeElement(desc, index)) encodeUnit() }
+    final override fun encodeNonSerializableElement(desc: SerialDescriptor, index: Int, value: Any) {
+        if (encodeElement(desc, index)) encodeValue(value)
+    }
+    @Deprecated(message = unitDeprecated, level = DeprecationLevel.ERROR)
+    final override fun encodeUnitElement(desc: SerialDescriptor, index: Int) {
```
Comment (sandwwraith) [inline runtime/commonMain/src/kotlinx/serialization/ElementWise.kt]: `encodeTaggedUnit` in `Tagged` should be deprecated, too

File: runtime/commonMain/src/kotlinx/serialization/Descriptors.kt [hunk 2]
```diff
@@ -11,7 +11,13 @@ sealed class SerialKind {
 
 sealed class PrimitiveKind : SerialKind() {
     object INT : PrimitiveKind()
+
+    @Deprecated(
+        message = "Primitive kind Unit is deprecated with no replacement. Use UnionKind.OBJECT instead or check for a particular serialName",
```
Comment (sandwwraith) [inline runtime/commonMain/src/kotlinx/serialization/Descriptors.kt]: Now it's `StructureKind.OBJECT` 🙃

File: runtime/commonMain/src/kotlinx/serialization/internal/ObjectSerializer.kt [hunk 3]
```diff
@@ -26,16 +26,14 @@ public class ObjectSerializer<T : Any>(serialName: String, private val objectIns
     }
 }
 
-private class ObjectDescriptor(name: String) : SerialClassDescImpl(name) {
+private class ObjectDescriptor(public override val serialName: String) : SerialDescriptor {
```
Comment (sandwwraith) [inline runtime/commonMain/src/kotlinx/serialization/internal/ObjectSerializer.kt]: don't forget to delete it on rebase
