### PR TITLE
Throw SerializationException instead of AIOB when ProtoBug encounters…

### LINKED ISSUE #1303: Protobuf: Unknown enum values cause ArrayIndexOutOfBoundsException
**Describe the bug**
During protobuf deserialization, if an unknown enum value is encountered, the deserializer throws an `ArrayIndexOutOfBoundsException` on the JVM instead of a `SerializationException`.

**To Reproduce**
See #1302 for a test case in the repo that produces the failure.

**Environment**
`master` at `b6eaad1974c6e544f230b0b4e6ccdf15e85ef209`
 - Kotlin platforms: JVM

### PR DESCRIPTION
**Pull request by qwwdfsad**
… unknown enum value

Fixes #1303

### CODE REVIEW

File: formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt [hunk 1]
```diff
@@ -90,7 +90,10 @@ internal open class ProtobufDecoder(
             if (protoId == protoTag) return i
         }
 
-        return -1
+        throw ProtobufDecodingException(
+            "$protoTag is not among valid ${descriptor.serialName} enum indicies, " +
+                    "values size is ${desc.elementNames}"
```
Comment (sandwwraith) [inline formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt:95]: Given that it is 'values size', maybe you meant `desc.elementsCount`? Anyway, count/size is not very helpful here because proto numbers can be arbitrary

**Review by sandwwraith — APPROVED** [review]

File: formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt (hunk 1 above)
Comment (qwwdfsad) [reply formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt]: Good spot
