### PR TITLE
Handle EOF in skipElement correctly

### LINKED ISSUE #1474: JSON decodeFromString never terminates with some invalid inputs (JsonLexer.skipElement loops infinitely) => huge battery drain.
Duplicating from https://youtrack.jetbrains.com/issue/KT-46611

Using Kotlin 1.5.0 with org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.0 (latest)

Given:
```
@Serializable
class Something

val json = Json { ignoreUnknownKeys = true }
```

.. this expression never terminates (with an exception) as it should, because the input is not valid JSON:
```
json.decodeFromString(Something.serializer(), """{"a":[{"b":[{"c":{}d",""e"":"}]}""")
```

Looks like the JsonLexer hits the end of input string, thus consumeNextToken() returns TC_EOF. After that, the while loop inside skipElement() keeps spinning forever.

### PR DESCRIPTION
**Pull request by sandwwraith**
Improve EOF exception in consumeStringLenient

Fixes #1474

### CODE REVIEW

File: formats/json/commonMain/src/kotlinx/serialization/json/internal/JsonLexer.kt [hunk 1]
```diff
@@ -445,16 +446,17 @@ internal class JsonLexer(private val source: String) {
...
                 TC_END_OBJ -> {
                     if (tokenStack.last() != TC_BEGIN_OBJ) throw JsonDecodingException(
                         currentPosition,
                         "found } instead of ]",
                         source
                     )
-                    tokenStack.removeAt(tokenStack.size - 1)
+                    tokenStack.removeLast()
                 }
+                TC_EOF -> fail("Unexpected end of input, possibly due to malformed JSON")
```
Comment (qwwdfsad) [inline formats/json/commonMain/src/kotlinx/serialization/json/internal/JsonLexer.kt:459]:
```suggestion
                TC_EOF -> fail("Unexpected end of input due to malformed JSON during ignoring unknown keys")
```

**Review by qwwdfsad — APPROVED** [review]
👍
