### PR TITLE
Retreive serializer for non-serializable enum on JVM

### LINKED ISSUE #913: Enum serializer is not found by its class
**Describe the bug**

Enum serializer is not found by its class

**To Reproduce**

```kotlin
enum class Status { OPEN, CLOSED }

fun main() {
    println(Json.encodeToString(Status.OPEN))
}
```

**Expected behavior**

Prints `"OPEN"`

**Actual**

```
Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'Status' is not found. Mark the class as @Serializable or provide the serializer explicitly.
```

### PR DESCRIPTION
**Pull request by qwwdfsad**
On the rest of the platforms this feature is blocked by KT-14743 (or plugin intrinsics). Anyway, providing the best possible user-experience only on the biggest platform is better than provide nothing, but consistently

Fixes #913

### CODE REVIEW

File: runtime/commonMain/src/kotlinx/serialization/internal/Enums.kt [hunk 1]
```diff
@@ -77,4 +76,6 @@ public class EnumSerializer<T : Enum<T>>(
         }
         return values[index]
     }
+
+    override fun toString(): String = "kotlinx.serialization.internal.EnumSerializer<${descriptor.serialName}>"
```
Comment (sandwwraith) [inline runtime/commonMain/src/kotlinx/serialization/internal/Enums.kt:80]: We usually do not have `toString()` on serializers, why is it needed?

File: runtime/commonTest/src/kotlinx/serialization/test/TestHelpers.kt [hunk 2]
```diff
@@ -9,7 +9,7 @@ import kotlinx.serialization.internal.EnumSerializer
 import kotlin.test.*
 
 @Suppress("TestFunctionName")
-inline fun <reified E : Enum<E>> EnumSerializer(serialName: String): EnumSerializer<E> =
+internal inline fun <reified E : Enum<E>> EnumSerializer(serialName: String): EnumSerializer<E> =
```
Comment (sandwwraith) [inline runtime/commonTest/src/kotlinx/serialization/test/TestHelpers.kt:12]: it is function in test sources anyway

File: runtime/jvmMain/src/kotlinx/serialization/internal/Platform.kt [hunk 3]
```diff
@@ -43,18 +43,31 @@ internal actual fun <T : Any> KClass<T>.constructSerializerForGivenTypeArgs(vara
...
     }
+
+    if (default != null) return default
+    // Fallback: enum without @Serializable annotation as last resort
+    return createEnumSerializer()
+}
+
+@Suppress("UNCHECKED_CAST")
+private fun <T : Any> KClass<T>.createEnumSerializer(): KSerializer<T>? {
+    if (!Enum::class.java.isAssignableFrom(java)) return null
```
Comment (sandwwraith) [inline runtime/jvmMain/src/kotlinx/serialization/internal/Platform.kt:60]:
```suggestion
    if (!Enum::class.java.isAssignableFrom(this.java)) return null
```

slightly more readable

File: runtime/jvmTest/src/kotlinx/serialization/features/SerializerByTypeTest.kt [hunk 4]
```diff
@@ -183,4 +183,12 @@ class SerializerByTypeTest {
         val superType = base::class.java.genericSuperclass!!
         return (superType as ParameterizedType).actualTypeArguments.first()!!
     }
+
+    enum class Foo
+
+    @Test
+    fun testNonSerializableEnum() {
+        val serializer = serializer<Foo>()
+        assertTrue { serializer.descriptor.kind is SerialKind.ENUM }
```
Comment (sandwwraith) [inline runtime/jvmTest/src/kotlinx/serialization/features/SerializerByTypeTest.kt:192]:
```suggestion
        assertTrue(serializer.descriptor.kind is SerialKind.ENUM)
```

no need for lambda, actually

File: runtime/commonMain/src/kotlinx/serialization/internal/Enums.kt (hunk 1 above)
Comment (qwwdfsad) [reply runtime/commonMain/src/kotlinx/serialization/internal/Enums.kt:80]: For better debugger experience when debugging formats/serializers

File: runtime/commonTest/src/kotlinx/serialization/test/TestHelpers.kt (hunk 2 above)
Comment (qwwdfsad) [reply runtime/commonTest/src/kotlinx/serialization/test/TestHelpers.kt:12]: it exposes internal `EnumSerializer` and should be internal

File: runtime/jvmTest/src/kotlinx/serialization/features/SerializerByTypeTest.kt (hunk 4 above)
Comment (qwwdfsad) [reply runtime/jvmTest/src/kotlinx/serialization/features/SerializerByTypeTest.kt:192]: Not sure what's the difference here, but okay

File: runtime/commonMain/src/kotlinx/serialization/internal/Enums.kt (hunk 1 above)
Comment (sandwwraith) [reply runtime/commonMain/src/kotlinx/serialization/internal/Enums.kt:80]: AFAIR, we once agreed that we should delegate `KSerializer.toString()` to `descriptor.toString()`, and this function doesn't follow this decision. It also doesn't help much until all serializers will have .toString(), so I suggest removing it for now
