### PR TITLE
Add decoding map in the root of HOCON config Fixes

### LINKED ISSUE #1046: Hcon: error while trying to decode MAP
**Describe the bug**

**bug.conf**
```
value1 {
    name = "name1",
    dir = "dir1"
    fileExtension = ".xlsx"
}

value2 {
    name = "name2",
    dir = "dir2"
    fileExtension = ".xlsx"
}

value3 {
    name = "name3",
    dir = "dir3"
    fileExtension = ".xlsx"
}
```

**code**
```
@Serializable
data class TestConfig(
    val name: String,
    val dir: String = "",
    val fileExtension: String = ".xlsx",
)

@ExperimentalSerializationApi
fun main() {
    val bugConfig = Files.newBufferedReader(Path.of("./bug.conf")).use(ConfigFactory::parseReader)
    val bugMap = Server.hoconParser.decodeFromConfig<Map<String, TestConfig>>(bugConfig)
}
```
**Exception**
```
Exception in thread "main" java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:380)
	at kotlinx.serialization.internal.TaggedDecoder.getCurrentTag(Tagged.kt:308)
	at kotlinx.serialization.hocon.Hocon$ConfigReader.beginStructure(Hocon.kt:138)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:243)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:179)
	at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:34)
	at TestKt.main(test.kt:194)
	at TestKt.main(test.kt)

```
error in code https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt#L138:
```
descriptor.kind == StructureKind.MAP -> MapConfigReader(conf.getObject(currentTag)) // currentTag NULL, tagStack: size 0
```

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: JVM
 - Gradle version: 6.6.1

### PR DESCRIPTION
**Pull request by shanshin**

### CODE REVIEW

File: formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconMapTest.kt [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+class HoconRootMapTest {
+    @Serializable
+    data class CompositeValue(
+            val a: String,
+            val b: Int
+    )
+
+    @Test
+    fun `config with root map`() {
```
Comment (qwwdfsad) [inline formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconMapTest.kt:38]: Backticked tests are legacy from the initial versions. We stick to `testFoo` naming convention.

File: formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconMapTest.kt [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+        val config = ConfigFactory.parseString(CONFIG_FOR_ROOT_MAP)
+        val hocon = Hocon {}
```
Comment (qwwdfsad) [inline formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconMapTest.kt:40]: You can use `Hocon` object: `Hocon.decodeFromConfig<...>(...)`

File: formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconMapTest.kt [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+ */
+
+package kotlinx.serialization.hocon
+
+import com.typesafe.config.ConfigFactory
+import kotlinx.serialization.Serializable
+import org.junit.Assert.assertEquals
+import org.junit.Test
+
+private const val CONFIG_FOR_ROOT_MAP = """
```
Comment (qwwdfsad) [inline formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconMapTest.kt:12]: Please embed it into the test class to have a single classfile. Don't insist tho

File: formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt [hunk 4]
```diff
@@ -141,7 +141,9 @@ public sealed class Hocon(
             when {
                 descriptor.kind.listLike -> ListConfigReader(conf.getList(currentTag))
                 descriptor.kind.objLike -> if (ind > -1) ConfigReader(conf.getConfig(currentTag)) else this
-                descriptor.kind == StructureKind.MAP -> MapConfigReader(conf.getObject(currentTag))
+                descriptor.kind == StructureKind.MAP ->
+                    //if current tag is null - map in the root of config
+                    MapConfigReader(if (currentTagOrNull != null) conf.getObject(currentTag) else conf.root())
```
Comment (qwwdfsad) [inline formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt:146]: This fix indeed fixes reported problem, but while we are here, I'd suggest to fix all similar problems consistently and thoughtfully.

What else here worth investigating:
- Top-level lists. If they are not supported in HOCON, then clear exception message
- Top-level primitives. Ditto as with lists
- Nullability. Test `Map<..>?` both when it's null (if it's supported) and when it's not. Same for lists/primitives

**Review by qwwdfsad — CHANGES_REQUESTED** [review]

File: formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt (hunk 4 above)
Comment (shanshin) [reply formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt:146]: 1. root-level lists supported in HOCON spec https://github.com/lightbend/config/blob/master/HOCON.md#syntax but typesafe config library support only subset of HOCON syntax https://github.com/lightbend/config/issues/460. So library not decode root-level lists
2. root-level primitives are not supported by HOCON and typesafe lib
3. root-level Map<>? supported but have unexpected behavior: if decode empty object "{}" not-null map reads as empty and nullable map reads as null. There is no way to define "null" config because primitives are illegal

File: formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt [hunk 5]
```diff
@@ -141,7 +141,9 @@ public sealed class Hocon(
             when {
                 descriptor.kind.listLike -> ListConfigReader(conf.getList(currentTag))
                 descriptor.kind.objLike -> if (ind > -1) ConfigReader(conf.getConfig(currentTag)) else this
-                descriptor.kind == StructureKind.MAP -> MapConfigReader(conf.getObject(currentTag))
+                descriptor.kind == StructureKind.MAP ->
+                    //if current tag is null - map in the root of config
```
Comment (sandwwraith) [inline formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt:145]:
```suggestion
                    // if current tag is null - map in the root of config
```

IMO, it's more readable. Most comments in codebase a written with this style (although capitalization differs, we probably need standard on that too)

File: formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+    }
+
+    @Test
+    fun testEmptyObjectDecode() {
+        val config = ConfigFactory.parseString(configWithEmptyObject)
+        //non-null map decoded from empty object as empty map
+        val map = Hocon.decodeFromConfig<Map<String, String>>(config)
+        assertTrue(map.isEmpty())
+
+        //nullable map decoded from empty object as null - not obvious
```
Comment (sandwwraith) [inline formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt:57]: I think this behavior is actually ok: given that `Hocon.decodeFromConfig<ComplexValue?>(emptyConfig)` returns null (or I really hope it does so, needs testing), this behavior is more consisntent that it may looks like at first sight.

Anyway, we can change it if we really want. Since original `config` is Java library, it seems that it cannot distinguish between nullable and non-null types, so this part is likely caused by our parser.

File: formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+        val nullableMap = Hocon.decodeFromConfig<Map<String, String>?>(config)
+        assertNull(nullableMap)
+
+        //root-level list in config not supported but nullable list can be decoded from empty object
+        val nullableList = Hocon.decodeFromConfig<List<String>?>(config)
+        assertNull(nullableList)
```
Comment (sandwwraith) [inline formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt:63]: It seems there's no need for separate variable and you can join lines: `assertNull(Hocon.decodeFromConfig<List<String>?>(config))`

File: formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+    fun testErrors() {
+        //because com.typesafe:config lib not support list in root we can't decode non-null list
+        val config = ConfigFactory.parseString(configWithEmptyObject)
+        var error: Exception? = null
+        try {
+            Hocon.decodeFromConfig<List<String>>(config)
+        } catch (e: NoSuchElementException) {
+            error = e
+        }
+        assertNotNull(error)
```
Comment (sandwwraith) [inline formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt:77]: It seems to me that this construction can be replaced with `assertFailsWith` function

File: formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt (hunk 6 above)
Comment (shanshin) [reply formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt:57]: Disagree. In case of static-size types (e.q. some custom ComplexValue) it's better to return null.

But as user with variable-size structure (Map) I expect size of map will be equals with JSON object properties count. In config object exists, so it's surprise for me - function behavior changed after changing return type to nullable, not changing of config string.
For example Jackson does as I said
objectMapper.readValue("{}", Map::class.java)  returns empty map and it is expected - I see begin object symbol and end object symbol - so object exists but not contains any properties.

Returning null is not a bug but some users can be confused this behavior.

Comment (sandwwraith) [reply formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt]: I've tested json and
```kotlin
        println(Json.decodeFromString<Map<String, String>>(emptyJson))
        println(Json.decodeFromString<Map<String, String>?>(emptyJson))
```

both give empty map as a result. And decoding even nullable user type from "{}" gives an error.

So we'd indeed better change that, if it's possible

Comment (shanshin) [reply formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt]: Change HOCON decoder behavior? In this PR?

Comment (sandwwraith) [reply formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt]: Yes

Comment (sandwwraith) [reply formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconRootObjectsTest.kt]: For this case (nullable map)

**Comment by sandwwraith** [comment]
Follow-up: #1157
