### PR TITLE
Fix incorrect json decoding iterator's .hasNext() behavior on array-wrapped inputs:

### LINKED ISSUE #2267: When using iterator from decodeToSequence, iterator.hasNext() throws when read all items and more
When using iterator created from Json.decodeToSequence<T> method and reading past all items, iterator.hasNext() will throw.
See the repro case where there are two elements in the list, while code tries to read 3 of them.

**To Reproduce**
```kotlin
val source = "[1, 2]"
val input = source.byteInputStream()
input.use {
    val iterator = Json.decodeToSequence<Int>(it).iterator()
    val values = iterator.asSequence().take(3).toList()
    var b = iterator.hasNext()  // throws
}
```

Exception is something like: Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Expected end of the array ']', but had 'EOF' instead at path: $

**Expected result**

`iterator.hasNext()` returns `false`.

**Environment**
 - Kotlin version: 1.8.0
 - Library version: 2.2.4
 - Kotlin platforms: JVM
 - Gradle version: 7.4.2

### PR DESCRIPTION
**Pull request by sandwwraith**
hasNext() shouldn't throw an exception if it was called more than once after the stream has ended.

Fixes #2267

### CODE REVIEW

File: formats/json/commonMain/src/kotlinx/serialization/json/internal/JsonIterator.kt [hunk 1]
```diff
@@ -84,6 +85,7 @@ private class JsonIteratorArrayWrapped<T>(
      */
     override fun hasNext(): Boolean {
         if (lexer.peekNextToken() == TC_END_LIST) {
+            sawClosingBrace = true
```
Comment (shanshin) [inline formats/json/commonMain/src/kotlinx/serialization/json/internal/JsonIterator.kt:88]: Perhaps it would be better to add the `finished` flag to check it at the very beginning of the `hasNext` function? like `if (finished) return false`

The difference is not fundamental, but it may be a little easier to read.

**Review by shanshin — APPROVED** [review]

File: formats/json/commonMain/src/kotlinx/serialization/json/internal/JsonIterator.kt (hunk 1 above)
Comment (sandwwraith) [reply formats/json/commonMain/src/kotlinx/serialization/json/internal/JsonIterator.kt:88]: Yeah, that makes sense
