### PR TITLE
Prohibited using of zero and negative filed number in ProtoNumber and zero field numbers in input bytes

### LINKED ISSUE #2649: OutOfMemoryError happens when try to decode the wrong ByteArray
**Describe the bug**
Sometimes our server get wrong ByteArray. We hoped the server throw wrong format error immediately when we try to decode the message. However, protobuf decoder blocks until java heap space out of memory error happens.

From our debugging, message is keep pushBacked by `reader.pushBackTag()` and index never moves forward from this method.
```ProtobufDecoding.kt
private fun decodeTaggedListIndex(): Int {
        val protoId = if (index == -1) {
            // For the very first element tag is already read by the parent
            reader.currentId
        } else {
            reader.readTag()
        }

        return if (protoId == tagOrSize.protoId) {
            ++index
        } else {
            // If we read tag of a different message, push it back to the reader and bail out
            reader.pushBackTag()
            CompositeDecoder.DECODE_DONE
        }
    }
```

**To Reproduce**
```
// class 
@Serializable
@SerialName("FrontRequest")
data class FrontRequest (
    val requests: List<String>,
) {
    companion object {
        @OptIn(ExperimentalSerializationApi::class)
        fun fromProtobuf(bytes: ByteArray): FrontRequest
            = ProtoBuf.decodeFromByteArray(bytes)
    }
}


//test 
val payloadBase64 = "+kCbAII+8m6eL8J/nzj6GfwQwzzAa6gzw2uhO8FJ/AGbOv9vr2y/P8l1o1SWPfcylGOnaMFroz7BOak6xGykapQ6qG6Sa/M5lD+jb5RupzvFbvBvxGmnbZVt9WiSaqY6yWL1bpQ/8z3EbvdpwG6pacRj9GrEbfI8xmr1OpM+o2nHPvBqwT7wb8Fup2g="
val payload = Base64.getDecoder().decode(payloadBase64)
//keep working until java heap space error
val frontRequestReceived = FrontRequest.fromProtobuf(payload)
```

// result
```
Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3609)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedBase.expand(ProtobufTaggedBase.kt:40)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedBase.pushTag(ProtobufTaggedBase.kt:34)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedBase.access$pushTag(ProtobufTaggedBase.kt:17)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:110)
	at com.dunamu.quot.realtime.front.request.FrontRequest$$serializer.deserialize(FrontRequest.kt:13)
```

**Expected behavior**
throw wrong format error immediately.

**Environment**
 - Kotlin version: 1.8.21
 - Library version: 1.5.1
 - Kotlin platforms: JVM
 - Gradle version: 7.5.1

### PR DESCRIPTION
**Pull request by shanshin**
Also optimized skipping of size delimited fields - removed the creation of an byte array in case of skipping

Fixes #2649

### CODE REVIEW

File: formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/Streams.kt [hunk 1]
```diff
@@ -33,6 +33,12 @@ internal class ByteArrayInput(private var array: ByteArray, private val endIndex
         return b
     }
 
+
+    fun scipExactNBytes(bytesCount: Int) {
```
Comment (sandwwraith) [inline formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/Streams.kt:37]: sKip :)

File: formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt [hunk 2]
```diff
@@ -45,8 +45,12 @@ internal open class ProtobufDecoder(
              * If we have reasonably small count of elements, try to build sequential
              * array for the fast-path. Fast-path implies that elements are not marked with @ProtoId
              * explicitly or are monotonic and incremental (maybe, 1-indexed)
+             *
+             * Since the library allows the use of fields with proto ID 0,
```
[the remark this answers is not in the document]
Comment (shanshin) [reply formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt:49]: Yes, this line isn't actual now, in this version I forbade the use of field number 0.

File: formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt [hunk 3]
```diff
@@ -45,8 +45,12 @@ internal open class ProtobufDecoder(
...
+             * it is necessary to initialize all elements, because there will always be one extra element
```
[the remark this answers is not in the document]
Comment (shanshin) [reply formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt:50]: if you look at the creation of the cache, there will be `IntArray(elements + 1)`.
This `+ 1` - is the `extra element`. 
This is because arrays are numbered from 0, and in protobuf fields start from 1, so in order to address properties from 1 to 32, we need 33 elements (element 0 should not have been used at all)

File: formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/Helpers.kt [hunk 4]
```diff
@@ -118,11 +119,21 @@ internal fun extractProtoId(descriptor: SerialDescriptor, index: Int, zeroBasedD
...
+                checkFieldNumber(result, i, descriptor)
+            }
         }
     }
     return result
 }
 
+private fun checkFieldNumber(fieldNumber: Int, propertyIndex: Int, descriptor: SerialDescriptor) {
+    if (fieldNumber <= 0) {
+        throw SerializationException("$fieldNumber is not allowed in ProtoNumber for property '${descriptor.getElementName(propertyIndex)}' of '${descriptor.serialName}', because protobuf support field numbers in range 1..${Int.MAX_VALUE}")
```
Comment (sandwwraith) [inline formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/Helpers.kt:133]:
```suggestion
        throw SerializationException("$fieldNumber is not allowed in ProtoNumber for property '${descriptor.getElementName(propertyIndex)}' of '${descriptor.serialName}', because protobuf supports field numbers in range 1..${Int.MAX_VALUE}")
```

File: formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/AutoAssignIdsTest.kt [hunk 5]
```diff
@@ -30,4 +30,15 @@ class AutoAssignIdsTest {
...
+
+    class NestedClass {
+        companion object
+    }
+
+    object X
+
+    @Test
+    fun testName() {
+        println(X::class.qualifiedName)
```
Comment (sandwwraith) [inline formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/AutoAssignIdsTest.kt:42]: Unrelated?

File: formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt [hunk 6]
```diff
@@ -45,8 +45,12 @@ internal open class ProtobufDecoder(
              * If we have reasonably small count of elements, try to build sequential
              * array for the fast-path. Fast-path implies that elements are not marked with @ProtoId
              * explicitly or are monotonic and incremental (maybe, 1-indexed)
+             *
+             * Initialize all elements, because there will always be one extra element as arrays are numbered from 0
+             * but in protobuf field number starts from 1.
```
Comment (sandwwraith) [inline formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt:50]: Either next line should be a complete sentence (it doesn't look like one now), or the dot shouldn't be here

File: formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/AutoAssignIdsTest.kt (hunk 5 above)
Comment (shanshin) [reply formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/AutoAssignIdsTest.kt]: Deleted

**Review by sandwwraith — APPROVED** [review]
