### PR TITLE
Fixed NoSuchMethodError when parsing a JSON stream on Java 8

### LINKED ISSUE #2326: NoSuchMethodError when parsing a JSON stream on Java 8
**Describe the bug**
Similar issue just with a different method:
#2218 

Java changed some function signatures on java 9, when building on java 9+ with targeting java 8, invalid bytecode is produced.  
java 9+ function: `ByteBuffer position(int newPosition)`
java 8 function: `Buffer position(int newPosition)`

**To Reproduce**
Attach a code snippet or test data if possible.
```kt
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import kotlinx.serialization.json.encodeToStream
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream

@Serializable
data class Data(val name: String, val entry: Int = 0)

@OptIn(ExperimentalSerializationApi::class)
fun main() {
    val out = ByteArrayOutputStream()
    Json.encodeToStream(Data("meow?", entry = 42), out)
    val inputStream = ByteArrayInputStream(out.toByteArray())
    Json.decodeFromStream<Data>(inputStream).let { println(it) } //⚡
}
```
will produce
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at kotlinx.serialization.json.internal.CharsetReader.fillByteBuffer(CharsetReader.kt:106)
	at kotlinx.serialization.json.internal.CharsetReader.doRead(CharsetReader.kt:78)
	at kotlinx.serialization.json.internal.CharsetReader.read(CharsetReader.kt:64)
	at kotlinx.serialization.json.internal.JavaStreamSerialReader.read(JvmJsonStreams.kt:261)
	at kotlinx.serialization.json.internal.ReaderJsonLexer.preload(JsonLexer.kt:87)
	at kotlinx.serialization.json.internal.ReaderJsonLexer.<init>(JsonLexer.kt:47)
	at kotlinx.serialization.json.internal.ReaderJsonLexer.<init>(JsonLexer.kt:38)
	at kotlinx.serialization.json.internal.JsonStreamsKt.decodeByReader(JsonStreams.kt:36)
	at kotlinx.serialization.json.JvmStreamsKt.decodeFromStream(JvmStreams.kt:61)
	at SerialBugDemoKt.main(SerialBugDemo.kt:20)
	at SerialBugDemoKt.main(SerialBugDemo.kt)

Process finished with exit code 1
```
**Expected behavior**
Not crashing

**Environment**
 - Kotlin version: 1.8.21
 - Library version: 1.5.1
 - Kotlin platforms: JVM **1.8** , newer JVM version don't crash
 - Gradle version: 8.1.1

### PR DESCRIPTION
**Pull request by shanshin**
Fixed NoSuchMethodError when parsing a JSON stream on Java 8

Fixes #2326

An explicit cast is needed here due to an API change in Java 9, see #2218.
In Java 8 and earlier, the `position(I)` method was final in `Buffer`, and returned a `Buffer`.
In Java 9 and later, the method was opened, and `ByteBuffer` overrides it, returning a `ByteBuffer`.
This causes a `NoSuchMethodError` when running a class, compiled with a newer Java version, on Java 8.

### CODE REVIEW

File: formats/json/jvmMain/src/kotlinx/serialization/json/internal/CharsetReader.kt [hunk 1]
```diff
@@ -103,7 +103,7 @@ internal class CharsetReader(
             val remaining = if (position <= limit) limit - position else 0
             val bytesRead = inputStream.read(byteBuffer.array(), byteBuffer.arrayOffset() + position, remaining)
             if (bytesRead < 0) return bytesRead
-            byteBuffer.position(position + bytesRead)
+            (byteBuffer as Buffer).position(position + bytesRead)
```
Comment (sandwwraith) [inline formats/json/jvmMain/src/kotlinx/serialization/json/internal/CharsetReader.kt:106]: Please add commentary like 'see the reasoning for cast in...'

**Review by sandwwraith — CHANGES_REQUESTED** [review]

**Review by sandwwraith — APPROVED** [review]
