### PR TITLE
Supply proper equals(), hashCode(), and toString() for SerialDescriptor() wrapper

### LINKED ISSUE #2941: WrappedSerialDescriptor.equals doesn't work
**Describe the bug**

Hi, I hit this while creating a generic custom serializer with our format-specific type support. My descriptor is like this

```
override val descriptor: SerialDescriptor = SerialDescriptor("android.util.SparseArray", surrogateSerializer.descriptor)
```

And I can't compare it in `encodeSerializableValue` as the comparison seems to be instance based.

**To Reproduce**
Attach a code snippet or test data if possible.

```
val a = SerialDescriptor("android.util.SparseArray", surrogateSerializer.descriptor)
val b = SerialDescriptor("android.util.SparseArray", surrogateSerializer.descriptor)
assertThat(a).isEqualTo(b)
```

**Expected behavior**

The test should pass, but I got:

```
java.lang.AssertionError: expected:<kotlinx.serialization.descriptors.WrappedSerialDescriptor@a47353e> but was:<kotlinx.serialization.descriptors.WrappedSerialDescriptor@e7ebf9f>
at org.junit.Assert.fail(Assert.java:89)
```

**Environment**
 - Kotlin version: 2.0.20
 - Library version: 1.8.0
 - Kotlin platforms: Android
 - Gradle version: 8.9

### PR DESCRIPTION
**Pull request by sandwwraith**
Fixes #2941

### CODE REVIEW

File: core/commonMain/src/kotlinx/serialization/descriptors/SerialDescriptors.kt [hunk 1]
```diff
@@ -121,7 +121,25 @@ public fun SerialDescriptor(serialName: String, original: SerialDescriptor): Ser
...
 
-internal class WrappedSerialDescriptor(override val serialName: String, original: SerialDescriptor) : SerialDescriptor by original
+internal class WrappedSerialDescriptor(override val serialName: String, private val original: SerialDescriptor) :
+    SerialDescriptor by original {
+
+    override fun equals(other: Any?): Boolean {
+        if (this === other) return true
+        if (other !is WrappedSerialDescriptor) return false
+
+        return serialName == other.serialName && original == other.original
```
Comment (shanshin) [inline core/commonMain/src/kotlinx/serialization/descriptors/SerialDescriptors.kt:131]: Is it ok if we check `serialName` inside `original`?

**Review by shanshin — APPROVED** [review]

File: core/commonMain/src/kotlinx/serialization/descriptors/SerialDescriptors.kt (hunk 1 above)
Comment (sandwwraith) [reply core/commonMain/src/kotlinx/serialization/descriptors/SerialDescriptors.kt:131]: Interesting point. Ideally, we should not check it. However, given that `equalsImpl` requires lambda to check type parameters, and we do not have any way to get them here, it seems that we can't avoid this check. 

At least, this should solve the case when the descriptor is identical, but object is created twice.
