### PR TITLE
Do not try to coerce input values for properties 

### LINKED ISSUE #2529: Misleading MissingFieldException on unexpected enum with coerceInputValues
**Describe the bug**
Json configuration option `coerceInputValues = true` is very helpful to future-proof network code, but it has some unfortunate side effects. Some of them are already raised in different issues, but this one is not (AFAIK):

When model has enum field with no default, and unexpected enum value is encountered, confusing `MissingFieldException` is thrown instead of correct exception with helpful error message. This caught me off-guard a couple times, causing time wasted looking for typos in field name, etc.

**To Reproduce**
```kotlin
@Test
fun `GIVEN json with unexpected enum value WHEN deserialize THEN throw meaningful exception`() {
    val jsonWithUnexpectedValue = """
        {
            "color": "SOMETHING_UNEXPECTED"
        }
    """.trimIndent()
    val jsonSerializer = Json {
        coerceInputValues = true
    }
    val throwable = runCatching {
        jsonSerializer.decodeFromString<Model>(jsonWithUnexpectedValue)
    }.exceptionOrNull()

    assertThat(throwable, instanceOf(SerializationException::class.java))
    assertThat(throwable!!.message, containsString("SOMETHING_UNEXPECTED"))
}

@Serializable
data class Model(val color: Color)

enum class Color { RED, GREEN }
```

**Expected behavior**
`kotlinx.serialization.SerializationException: gmk57.Color does not contain element with name 'SOMETHING_UNEXPECTED' at path $.color`
That's what is thrown with `coerceInputValues = false`

**Observed behavior**
`kotlinx.serialization.MissingFieldException: Field 'color' is required for type with serial name 'gmk57.Model', but it was missing at path: $`

**Environment**
 - Kotlin version: 1.9.10
 - Library version: 1.6.2

I guess the root cause is the same as in #1947, but the issue we face is a bit different.

### PR DESCRIPTION
**Pull request by sandwwraith**
that do not have default values

Trying so leads to confusing errors about missing values despite a json key actually present in the input.

Fixes #2529

### CODE REVIEW

File: formats/json/commonMain/src/kotlinx/serialization/json/Json.kt [hunk 1]
```diff
@@ -287,7 +287,7 @@ public class JsonBuilder internal constructor(json: Json) {
     public var prettyPrintIndent: String = json.configuration.prettyPrintIndent
 
     /**
-     * Enables coercing incorrect JSON values to the default property value in the following cases:
+     * Enables coercing incorrect JSON values to the default property value (if exists) in the following cases:
```
Comment (shanshin) [inline formats/json/commonMain/src/kotlinx/serialization/json/Json.kt:290]: M.b. `if specified`?

**Review by shanshin — APPROVED** [review]

File: formats/json/commonMain/src/kotlinx/serialization/json/Json.kt (hunk 1 above)
Comment (sandwwraith) [reply formats/json/commonMain/src/kotlinx/serialization/json/Json.kt:290]: I think `if specified` may be incorrectly read as `if coerceInputValues = true is specified`
