### PR TITLE
Do not try to end structure in encode/decode stucture extensions if a…

### LINKED ISSUE #1187: decodeStructure swallows exceptions
Exceptions thrown within the decodeStructure block are swallowed.

This code:

```    
decoder.decodeStructure(descriptor) {
        TODO()
    }
```

throws an JsonDecodingException:
Unexpected JSON token at offset 1: Expected '}'

I assume the original exception is hidden, because the decoder tries to finish decoding the JSON object.

I strongly prefer to have the the original exception thrown.

### PR DESCRIPTION
**Pull request by qwwdfsad**
…n exception has been thrown, so the original exception will be propagated

Fixes #1187

### CODE REVIEW

File: core/commonMain/src/kotlinx/serialization/encoding/Decoding.kt [hunk 1]
```diff
@@ -524,10 +524,15 @@ public inline fun <T> Decoder.decodeStructure(
     block: CompositeDecoder.() -> T
 ): T {
     val composite = beginStructure(descriptor)
+    var ex: Throwable? = null
```
Comment (sandwwraith) [inline core/commonMain/src/kotlinx/serialization/encoding/Decoding.kt:527]: Wouldn't it be the same just to write

```kotlin
val composite = beginStructure(descriptor)
val result = composite.block()
composite.endStructure()
return result
```

without all try-catch logic?

Comment (qwwdfsad) [reply core/commonMain/src/kotlinx/serialization/encoding/Decoding.kt:527]: It's going to break for a `return` statement.
And marking it with `crossinline` makes things less pretty

**Review by sandwwraith — APPROVED** [review]
