### PR TITLE
Fix infinite recursion in EnumDescriptor.hashCode()

### LINKED ISSUE #666: Enum Descriptor causes infinite recursion and Stack Overflow
**Describe the bug**
I want to iterate over Enum Descriptor, but I suddenly understand that I can't do almost anything: exceptions are thrown.

Something related to Descriptor For Nullable happens here too: results differ for classes with different nullability of properties.

**To Reproduce**
I think all tests here should pass:

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.elementDescriptors
import kotlin.test.Test

@Serializable
data class Data1(val a: A)

@Serializable
data class Data2(val a: A?)

@Serializable
enum class A {

  B,
}

class EnumDescriptorTest {

  @Test
  fun test1() {
    val a = Data1.serializer().descriptor.elementDescriptors().joinToString()
    println("test1: $a")
  }

  @Test
  fun test2() {
    val a = Data2.serializer().descriptor.elementDescriptors().joinToString()
    println("test2: $a")
  }

  @Test
  fun test3() {
    val a = Data1.serializer().descriptor.hashCode()
    println("test3: $a")
  }

  @Test
  fun test4() {
    val a = Data2.serializer().descriptor.hashCode()
    println("test4: $a")
  }

  @Test
  fun test5() {
    val a = A.serializer().descriptor.hashCode()
    println("test5: $a")
  }
}
```

**Expected behavior**
However, only the first test passes and others fail with stack overflow error:

```
java.lang.StackOverflowError
	at kotlinx.serialization.ShorthandsKt.elementDescriptors(Shorthands.kt:34)
	at kotlinx.serialization.internal.SerialClassDescImpl.hashCode(SerialClassDescImpl.kt:91)
	at kotlinx.serialization.internal.EnumDescriptor.hashCode(Enums.kt:41)
	at java.base/java.util.ArrayList.hashCodeRange(ArrayList.java:626)
	at java.base/java.util.ArrayList.hashCode(ArrayList.java:613)
	at kotlinx.serialization.internal.SerialClassDescImpl.hashCode(SerialClassDescImpl.kt:91)
	at kotlinx.serialization.internal.EnumDescriptor.hashCode(Enums.kt:41)
	at java.base/java.util.ArrayList.hashCodeRange(ArrayList.java:626)
	at java.base/java.util.ArrayList.hashCode(ArrayList.java:613)
	at kotlinx.serialization.internal.SerialClassDescImpl.hashCode(SerialClassDescImpl.kt:91
and so on
```

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: tested on JVM
 - Gradle version: 5.2.1
 - Other relevant context: JRE is JBR11, OS is Linux

### PR DESCRIPTION
**Pull request by sandwwraith**
Specify NullableDescriptor.toString()

Fixes #666

### CODE REVIEW

File: runtime/commonTest/src/kotlinx/serialization/EnumSerializationTest.kt [hunk 1]
```diff
@@ -66,4 +78,34 @@ class EnumSerializationTest : JsonTestBase() {
             CustomInside.serializer(),
             CustomInside(WithCustom.TWO), """{inside:2}"""
         )
+
+
+    @Test
+    fun hasMeaningfulToString() {
```
Comment (qwwdfsad) [inline runtime/commonTest/src/kotlinx/serialization/EnumSerializationTest.kt]: please use `test` prefix consistently
