### PR TITLE
Do not remove type discriminator in unsafe manner during polymorphic …

### LINKED ISSUE #807: java.util.NoSuchElementException when deserializing twice from the same JsonElement
Steps to reproduce:
```
@Serializable
sealed class Foo {
    @Serializable
    data class Bar(val a: Int) : Foo()
}
@Test
fun testFoo() {
    val json = Json.toJson(Foo.Bar(1))
    println(Json.fromJson<Foo>(json))
    println(Json.fromJson<Foo>(json))
}
```

### PR DESCRIPTION
**Pull request by qwwdfsad**
…JSON deserializer, properly filter out it in unknown keys check instead

Fixes #807

### CODE REVIEW

**Comment by qwwdfsad** [comment]
The commit fails because of problems in K/N. PTAL

File: runtime/commonMain/src/kotlinx/serialization/json/internal/TreeJsonInput.kt [hunk 1]
```diff
@@ -155,12 +168,23 @@ private open class JsonTreeInput(json: Json, override val value: JsonObject) : A
 
     override fun currentElement(tag: String): JsonElement = value.getValue(tag)
 
+    override fun beginStructure(descriptor: SerialDescriptor): CompositeDecoder {
+        /*
+         * For polymorphic serialization we'd like to avoid excessive decoder creating in
+         * beginStructure to properly preserve 'polyDiscriminator' field and filter it out.
+         */
+        if (descriptor == polyDescriptor) return this
```
Comment (sandwwraith) [inline runtime/commonMain/src/kotlinx/serialization/json/internal/TreeJsonInput.kt:176]: Can we use `===` here?

File: runtime/commonTest/src/kotlinx/serialization/features/PolymorphismTest.kt [hunk 2]
```diff
@@ -48,6 +48,7 @@ class PolymorphismTest : JsonTestBase() {
 
     object PolyDefaultSerializer : JsonTransformingSerializer<PolyDefault>(PolyDefault.serializer(), "foo") {
         override fun readTransform(element: JsonElement): JsonElement {
+            (element.jsonObject.content as MutableMap).remove("type")
```
Comment (sandwwraith) [inline runtime/commonTest/src/kotlinx/serialization/features/PolymorphismTest.kt:51]: I'd like to avoid such hacks in test code, because it may be an example for someone.

File: runtime/commonTest/src/kotlinx/serialization/json/polymorphic/JsonDeserializePolymorphicTwiceTest.kt [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+
+    @Serializable
+    sealed class Foo {
+        @Serializable
+        data class Bar(val a: Int) : Foo()
+    }
+
+    @Test
+    fun testDeserializeTwice() {
+        val json = Json.toJson(Foo.Bar(1) as Foo)
```
Comment (sandwwraith) [inline runtime/commonTest/src/kotlinx/serialization/json/polymorphic/JsonDeserializePolymorphicTwiceTest.kt:21]: it seems like sealed classes do not have special `AssociatedObject`, so this lookup won't work. I'll address it as a separate issue

Comment (sandwwraith) [reply runtime/commonTest/src/kotlinx/serialization/json/polymorphic/JsonDeserializePolymorphicTwiceTest.kt:21]: #812

File: runtime/commonTest/src/kotlinx/serialization/features/PolymorphismTest.kt (hunk 2 above)
Comment (sandwwraith) [reply runtime/commonTest/src/kotlinx/serialization/features/PolymorphismTest.kt:51]: Seems you forgot to delete the line after fix?

File: runtime/commonTest/src/kotlinx/serialization/json/polymorphic/JsonDeserializePolymorphicTwiceTest.kt [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+
+    @Serializable
+    sealed class Foo {
+        @Serializable
+        data class Bar(val a: Int) : Foo()
+    }
+
+    @Test
+    fun testDeserializeTwice() = noNative { // #812
+        val json = Json.toJson(Foo.Bar(1) as Foo)
```
Comment (sandwwraith) [inline runtime/commonTest/src/kotlinx/serialization/json/polymorphic/JsonDeserializePolymorphicTwiceTest.kt:22]: I'd rather use `Json.toJson(Foo.serializer(), Foo.Bar(1))` instead of ignoring test on Native completely
