### PR TITLE
Fixed type discriminator value for custom serializer that uses `encodeJsonElement`

### LINKED ISSUE #2451: Polymorphism with custom serializer which writes JsonObject outputs incorrect class discriminator
**Describe the bug**
`"type":"kotlin.collections.LinkedHashMap"` is an incorrect discriminator and prevents data from de-serialization

**To Reproduce**
```
@Serializable
data class ValueHolder<V : Any>(
    val someField: Int,
    @Polymorphic val value: V,
)

@Serializable
data class DataStructure<V : Any>(
    val holders: List<ValueHolder<V>>
)

data class VImpl(val a: String, val b: Int)

class E {
    val serializer = object : KSerializer<VImpl> {
        override val descriptor: SerialDescriptor =
            buildClassSerialDescriptor("VImpl") {
                element("a", String.serializer().descriptor)
                element("b", Int.serializer().descriptor)
            }

        override fun deserialize(decoder: Decoder): VImpl {
            decoder as JsonDecoder
            val jsonObject = decoder.decodeJsonElement() as JsonObject
            return VImpl(
                (jsonObject["a"] as JsonPrimitive).toString(),
                (jsonObject["b"] as JsonPrimitive).int,
            )
        }

        override fun serialize(encoder: Encoder, value: VImpl) {
            encoder as JsonEncoder
            encoder.encodeJsonElement(
                JsonObject(
                    mapOf(
                        "a" to JsonPrimitive(value.a),
                        "b" to JsonPrimitive(value.b)
                    )
                )
            )
        }
    }


    @Test
    fun main() {
        val dataStructure = DataStructure(listOf(ValueHolder(0, VImpl("string", 1))))

        val json = Json {
            serializersModule = SerializersModule {
                polymorphic(Any::class, VImpl::class, serializer)
            }
        }

        val string = json.encodeToString(
            DataStructure.serializer(serializer),
            dataStructure
        )
        println(string)
    }

}
```
**Expected behavior**
Data can be deserialized back

**Environment**
 - Kotlin version: 1.9.0
 - Library version: 1.6.0

### PR DESCRIPTION
**Pull request by shanshin**
Fixes #2451

### CODE REVIEW

File: formats/json-tests/commonTest/src/kotlinx/serialization/features/PolymorphismForCustomTest.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+import kotlinx.serialization.modules.*
+import kotlin.test.*
+
+class PolymorphismForCustomTest : JsonTestBase() {
+
+    private val customSerializer = object : KSerializer<VImpl> {
+        override val descriptor: SerialDescriptor =
+            buildClassSerialDescriptor("VImpl") {
+                element("a", String.serializer().descriptor)
+                element("b", Int.serializer().descriptor)
```
Comment (sandwwraith) [inline formats/json-tests/commonTest/src/kotlinx/serialization/features/PolymorphismForCustomTest.kt:21]: There's no `b` in VImpl though

File: formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt [hunk 2]
```diff
@@ -16,7 +16,7 @@ import kotlin.jvm.*
 internal inline fun <T> JsonEncoder.encodePolymorphically(
     serializer: SerializationStrategy<T>,
     value: T,
-    ifPolymorphic: (String) -> Unit
+    ifPolymorphic: (String, String) -> Unit
```
Comment (sandwwraith) [inline formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt:19]: [nit] It will be easier to understand if function type had parameter names:

```suggestion
    ifPolymorphic: (discriminatorName: String, serialName: String) -> Unit
```

File: formats/json/commonMain/src/kotlinx/serialization/json/internal/TreeJsonEncoder.kt [hunk 3]
```diff
@@ -155,7 +158,14 @@ private sealed class AbstractJsonTreeEncoder(
 
         val discriminator = polymorphicDiscriminator
         if (discriminator != null) {
-            encoder.putElement(discriminator, JsonPrimitive(polymorphicSerialName ?: descriptor.serialName))
+            if (encoder is JsonTreeMapEncoder) {
+                // first parameter is ignored in JsonTreeMapEncoder
```
Comment (sandwwraith) [inline formats/json/commonMain/src/kotlinx/serialization/json/internal/TreeJsonEncoder.kt:162]: I don't get what 'first parameter' you are referring to

**Review by sandwwraith — APPROVED** [review]
LGTM. Did you check that if doesn't fix all related issues?

File: formats/json/commonMain/src/kotlinx/serialization/json/internal/TreeJsonEncoder.kt (hunk 3 above)
Comment (shanshin) [reply formats/json/commonMain/src/kotlinx/serialization/json/internal/TreeJsonEncoder.kt:162]: First parameter in implementation of `putElement` for `JsonTreeMapEncoder`
```
    override fun putElement(key: String, element: JsonElement) {
        if (isKey) { // writing key
            tag = when (element) {
                is JsonPrimitive -> element.content
                is JsonObject -> throw InvalidKeyKindException(JsonObjectSerializer.descriptor)
                is JsonArray -> throw InvalidKeyKindException(JsonArraySerializer.descriptor)
            }
            isKey = false
        } else {
            content[tag] = element
            isKey = true
        }
    }
```
`key` - is unused

Comment (sandwwraith) [inline formats/json/commonMain/src/kotlinx/serialization/json/internal/TreeJsonEncoder.kt:162]:
```suggestion
                // first parameter of `putElement` is ignored in JsonTreeMapEncoder
```

**Comment by shanshin** [comment]
> LGTM. Did you check that if doesn't fix all related issues?

Unfortunately, no, other issues concern sealed classes
