### PR TITLE
Fixed serializers caching for parametrized types from different class loaders

### LINKED ISSUE #2065: Regression in 1.4.1: serializers cache does not distinguish the same class loaded by multiple classloaders
See 
https://youtrack.jetbrains.com/issue/KT-54523/Regression-kotlinxserialization-141-caches-the-same-serializer-for-ArrayListFoo-for-ktypes-from-different-class-loaders

### PR DESCRIPTION
**Pull request by shanshin**
Fixes #2065

### CODE REVIEW

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt [hunk 1]
```diff
@@ -101,10 +103,37 @@ private class ConcurrentHashMapParametrizedCache<T>(private val compute: (KClass
...
+    override fun equals(other: Any?): Boolean {
+        if (other == null) return false
+        if (origin != other) return false
+
+        if (classifier is KClass<*>) {
+            val otherClassifier = (other as? KType)?.classifier
+            if (otherClassifier == null || otherClassifier !is KClass<*>) {
+                return false
+            }
+            return classifier.java == otherClassifier.java
```
Comment (sandwwraith) [inline core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:121]: `KClassImpl` uses `javaObjectType` instead of `java`: https://github.com/JetBrains/kotlin/blob/bfa3f89aeb727518703f0a167153cb048724a6d1/core/reflection.jvm/src/kotlin/reflect/jvm/internal/KClassImpl.kt#L293

I'm not sure why, but maybe this difference is important

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt [hunk 2]
```diff
@@ -101,10 +103,37 @@ private class ConcurrentHashMapParametrizedCache<T>(private val compute: (KClass
...
+    override val annotations: List<Annotation> = origin.annotations
+    override val arguments: List<KTypeProjection> = origin.arguments
+    override val classifier: KClassifier? = origin.classifier
+    override val isMarkedNullable: Boolean = origin.isMarkedNullable
+
+    override fun equals(other: Any?): Boolean {
+        if (other == null) return false
+        if (origin != other) return false
+
+        if (classifier is KClass<*>) {
```
Comment (sandwwraith) [inline core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:116]: `classifier` can also be a `ClassReference` (https://github.com/JetBrains/kotlin/blob/6ddca4a592542ae1b800f5f04ec42d9c48464a80/libraries/stdlib/jvm/runtime/kotlin/jvm/internal/ClassReference.kt#L10) but I don't know whether it appears anywhere in real life.
Maybe @udalov knows

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt [hunk 3]
```diff
@@ -101,10 +103,37 @@ private class ConcurrentHashMapParametrizedCache<T>(private val compute: (KClass
 
 private class CacheEntry<T>(@JvmField val serializer: KSerializer<T>?)
 
+private class KTypeWrapper(val origin: KType): KType {
```
Comment (sandwwraith) [inline core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:106]: This should be a temporary counter-measure, because problem should be fixed in kotlin-reflect. Can you create youtrack ticket and drop a comment with it here?

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt [hunk 4]
```diff
@@ -101,10 +103,37 @@ private class ConcurrentHashMapParametrizedCache<T>(private val compute: (KClass
...
+            if (otherClassifier == null || otherClassifier !is KClass<*>) {
+                return false
+            }
+            return classifier.java == otherClassifier.java
+        } else {
+            return false
+        }
+    }
+
+    override fun hashCode(): Int {
```
Comment (sandwwraith) [inline core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:127]: You can also add `toString()` for debuggability reasons

File: formats/json-tests/jvmTest/src/kotlinx/serialization/SerializerByTypeCacheTest.kt [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+     *
+     * As a result, a serializer for another loader will be returned from the cache, and it will generate instances, when working with which we will get an [ClassCastException].
+     *
+     * The test checks the correctness of the cache for such cases - that different serializers for different loaders will be returned.
+     *
+     * [see](https://youtrack.jetbrains.com/issue/KT-54523).
+     */
+    @Test
+    fun testDifferentClassLoaders() {
+        val elementKType1 = SimpleKType(loadClass().kotlin)
```
Comment (sandwwraith) [inline formats/json-tests/jvmTest/src/kotlinx/serialization/SerializerByTypeCacheTest.kt:43]: Is there any way to test this on real `KTypeImpl` instead of hand-rolled?

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt (hunk 2 above)
Comment (shanshin) [reply core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:116]: `ClassReference` implements `KClass`

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt (hunk 1 above)
Comment (shanshin) [reply core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:121]: As far as I understand, `javaObjectType` also handles primitives, but in our case primitives cannot parameterize types.

File: formats/json-tests/jvmTest/src/kotlinx/serialization/SerializerByTypeCacheTest.kt (hunk 5 above)
Comment (shanshin) [reply formats/json-tests/jvmTest/src/kotlinx/serialization/SerializerByTypeCacheTest.kt:43]: In this case, it will be necessary to add a dependency on `kotlin-reflect` for all tests.

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt (hunk 2 above)
Comment (udalov) [reply core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:116]: `X::class` is an expression of type `KClass` which
1) if you have `kotlin-reflect.jar` in classpath, creates an object of type `KClassImpl`
2) if you don't, it creates `ClassReference`

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt (hunk 3 above)
Comment (qwwdfsad) [reply core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:106]: https://youtrack.jetbrains.com/issue/KT-54611

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt (hunk 2 above)
Comment (sandwwraith) [reply core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:116]: 🤦🏻 didn't notice that it already implements KClass

File: core/jvmMain/src/kotlinx/serialization/internal/Caching.kt [hunk 6]
```diff
@@ -101,10 +103,49 @@ private class ConcurrentHashMapParametrizedCache<T>(private val compute: (KClass
 
 private class CacheEntry<T>(@JvmField val serializer: KSerializer<T>?)
 
+/**
+ * Workaround of https://youtrack.jetbrains.com/issue/KT-54611 and https://github.com/Kotlin/kotlinx.serialization/issues/2065
+ */
+private class KTypeWrapper(val origin: KType) : KType {
```
Comment (qwwdfsad) [inline core/jvmMain/src/kotlinx/serialization/internal/Caching.kt:109]:
```suggestion
private class KTypeWrapper(private val origin: KType) : KType {
```

**Review by qwwdfsad — APPROVED** [review]
